// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gossip.proto

package gossip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_NEW     Status = 0
	Status_SUSPECT Status = 2
	Status_DEAD    Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "NEW",
		2: "SUSPECT",
		3: "DEAD",
	}
	Status_value = map[string]int32{
		"NEW":     0,
		"SUSPECT": 2,
		"DEAD":    3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_gossip_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_gossip_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{0}
}

type GossipMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ListHash      []byte                 `protobuf:"bytes,3,opt,name=list_hash,json=listHash,proto3" json:"list_hash,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Version       uint32                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Diff          []*NodeUpdates         `protobuf:"bytes,2,rep,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMsg) Reset() {
	*x = GossipMsg{}
	mi := &file_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMsg) ProtoMessage() {}

func (x *GossipMsg) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMsg.ProtoReflect.Descriptor instead.
func (*GossipMsg) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *GossipMsg) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GossipMsg) GetListHash() []byte {
	if x != nil {
		return x.ListHash
	}
	return nil
}

func (x *GossipMsg) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *GossipMsg) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GossipMsg) GetDiff() []*NodeUpdates {
	if x != nil {
		return x.Diff
	}
	return nil
}

type NodeUpdates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIp        string                 `protobuf:"bytes,1,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeUpdates) Reset() {
	*x = NodeUpdates{}
	mi := &file_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUpdates) ProtoMessage() {}

func (x *NodeUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUpdates.ProtoReflect.Descriptor instead.
func (*NodeUpdates) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *NodeUpdates) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *NodeUpdates) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_NEW
}

var File_gossip_proto protoreflect.FileDescriptor

const file_gossip_proto_rawDesc = "" +
	"\n" +
	"\fgossip.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\tGossipMsg\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tlist_hash\x18\x03 \x01(\fR\blistHash\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12 \n" +
	"\x04diff\x18\x02 \x03(\v2\f.NodeUpdatesR\x04diff\"G\n" +
	"\vNodeUpdates\x12\x17\n" +
	"\anode_ip\x18\x01 \x01(\tR\x06nodeIp\x12\x1f\n" +
	"\x06status\x18\x02 \x01(\x0e2\a.StatusR\x06status*(\n" +
	"\x06Status\x12\a\n" +
	"\x03NEW\x10\x00\x12\v\n" +
	"\aSUSPECT\x10\x02\x12\b\n" +
	"\x04DEAD\x10\x03B\x0fZ\rpb/gen/gossipb\x06proto3"

var (
	file_gossip_proto_rawDescOnce sync.Once
	file_gossip_proto_rawDescData []byte
)

func file_gossip_proto_rawDescGZIP() []byte {
	file_gossip_proto_rawDescOnce.Do(func() {
		file_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)))
	})
	return file_gossip_proto_rawDescData
}

var file_gossip_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gossip_proto_goTypes = []any{
	(Status)(0),                   // 0: Status
	(*GossipMsg)(nil),             // 1: GossipMsg
	(*NodeUpdates)(nil),           // 2: NodeUpdates
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_gossip_proto_depIdxs = []int32{
	3, // 0: GossipMsg.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: GossipMsg.diff:type_name -> NodeUpdates
	0, // 2: NodeUpdates.status:type_name -> Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gossip_proto_init() }
func file_gossip_proto_init() {
	if File_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gossip_proto_goTypes,
		DependencyIndexes: file_gossip_proto_depIdxs,
		EnumInfos:         file_gossip_proto_enumTypes,
		MessageInfos:      file_gossip_proto_msgTypes,
	}.Build()
	File_gossip_proto = out.File
	file_gossip_proto_goTypes = nil
	file_gossip_proto_depIdxs = nil
}
